version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_HTTP_PORT: 8180
    command: start-dev --http-port 8180
    ports:
      - "8180:8180"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
